import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Helmet } from 'react-helmet-async';
import { Button } from '../components/ui/Button.jsx';
import { isCounselorSubdomain } from '../lib/subdomain.js';

const VERIREC_FAQS = [
  {
    q: 'Is VeriRec compliant with the Personal Data Protection Act (PDPA) 2010?',
    a: 'Yes. VeriRec is designed specifically for PDPA Malaysia compliance. Every session requires a digitally signed informed consent form with timestamp, version, and a non-deletable audit trail. Consent data is retained permanently as a compliance record.',
  },
  {
    q: 'Where is my recording and transcript data stored?',
    a: 'All data is stored on Supabase servers located in the Asia Pacific region (Singapore). Data is encrypted in transit (TLS 1.3) and at rest (AES-256). No data leaves this secure infrastructure.',
  },
  {
    q: 'What is the SHA-256 hash and how does it work?',
    a: 'Every report generated by VeriRec has a unique digital fingerprint (SHA-256 hash) computed from the report and transcript content. If anyone attempts to alter the report after it is generated, the hash will change and verification will fail. This proves document authenticity — critical for court evidence and official investigations.',
  },
  {
    q: 'Can I delete recordings and session data?',
    a: 'Yes, you can delete sessions from the dashboard. However, consent data cannot be deleted — this is a PDPA requirement to retain consent records permanently. Audio recordings can be deleted separately if needed.',
  },
  {
    q: 'What audio formats are supported?',
    a: 'VeriRec uses the MediaRecorder API which automatically selects the best format for your device — WebM/Opus for Chrome/Android, MP4/AAC for Safari/iOS. No manual configuration is needed.',
  },
  {
    q: 'Does VeriRec work without an internet connection?',
    a: 'Yes, partially. You can record and view transcripts offline. Session data is stored locally (IndexedDB) and will sync to the server when the connection is restored. However, AI report generation requires an internet connection.',
  },
  {
    q: 'Can I export reports in other formats?',
    a: 'Yes. Reports can be printed directly from the browser or exported as PDF. The PDF export uses A4 format and includes all report information including the SHA-256 hash for verification.',
  },
  {
    q: 'How do I cancel my subscription?',
    a: 'You can cancel your subscription at any time from the Settings page. Cancellation takes effect at the end of the current billing period — you retain access to all paid features until then.',
  },
  {
    q: 'Is VeriRec suitable for use in court proceedings?',
    a: 'VeriRec is designed to facilitate professional documentation. The SHA-256 hash serves as proof of document integrity. However, admissibility as court evidence depends on Malaysian court rules and specific cases. Please seek legal advice for specific cases.',
  },
  {
    q: 'How do I contact technical support?',
    a: 'Send an email to hello@verirec.app. Typical response time is within 24 hours on business days. Business plan customers receive priority support with a 4-hour response time.',
  },
];

const KAUNSELOR_FAQS = [
  {
    q: 'Is Kaunselor compliant with privacy and data protection regulations?',
    a: 'Yes. Kaunselor is built to meet global data protection standards including the Personal Data Protection Act 2010 (PDPA) of Malaysia and GDPR-equivalent principles. Every session records informed consent digitally with a permanent, non-deletable audit trail.',
  },
  {
    q: 'Where is my client data stored?',
    a: 'All data is stored on Supabase servers in the Asia Pacific region (Singapore). Data is encrypted in transit (TLS 1.3) and at rest (AES-256). Your client data never leaves this secure infrastructure and is never used to train AI models.',
  },
  {
    q: 'Can clients book appointments themselves?',
    a: 'Yes. Every counselor gets a unique QR code and booking link. Clients scan or click the link, choose an available slot, and submit a request — you then approve or decline. No app download required for clients.',
  },
  {
    q: 'What are the MBTI and RIASEC assessments?',
    a: 'MBTI (Myers-Briggs Type Indicator) is a 16-question personality assessment. RIASEC (Holland Code) is a 24-activity career interest tool. Both are built directly into the session view — you can run them with clients during a session and results are saved automatically to the client file.',
  },
  {
    q: 'How does the AI session report work?',
    a: 'After a session, Kaunselor\'s AI (powered by Anthropic Claude) analyses the session transcript and generates a structured counseling note including presenting issues, session summary, risk indicators, and recommended follow-up actions. You can edit the report before saving or exporting.',
  },
  {
    q: 'Can I export session notes as PDF?',
    a: 'Yes. Every session report can be exported as a professional PDF in A4 format, including client details, session summary, assessment results, and follow-up plan. Case files can also be exported as a bundled PDF.',
  },
  {
    q: 'Does Kaunselor work without an internet connection?',
    a: 'Yes, partially. You can record sessions and view transcripts offline. Data is stored locally and syncs automatically when your connection is restored. AI report generation and appointment management require an internet connection.',
  },
  {
    q: 'Is the $25/month price in USD? Can I pay in my local currency?',
    a: 'Yes, pricing is in USD ($25/month). Stripe — our payment processor — supports most major currencies and will convert to your local currency at checkout. You can pay by credit or debit card from anywhere in the world.',
  },
  {
    q: 'What happens to my data if I cancel?',
    a: 'You can cancel your subscription at any time from Settings. You retain access until the end of the current billing period. Your data is kept for 30 days after account closure before deletion, except for consent records which are retained permanently as required by law.',
  },
  {
    q: 'How do I contact support?',
    a: 'Email us at hello@kaunselor.app. We typically respond within 24 hours on business days. We\'re happy to help with setup, technical issues, or any questions about the platform.',
  },
];

function FaqItem({ q, a, accent }) {
  const [open, setOpen] = useState(false);
  return (
    <div className="border-b border-gray-200 last:border-0">
      <button
        className="w-full text-left py-5 flex items-start justify-between gap-4 group"
        onClick={() => setOpen(!open)}
      >
        <span className={`font-medium text-gray-900 group-hover:${accent} transition-colors`}>{q}</span>
        <span className={`flex-shrink-0 mt-0.5 text-gray-400 transition-transform ${open ? 'rotate-180' : ''}`}>
          <svg xmlns="http://www.w3.org/2000/svg" className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M19 9l-7 7-7-7" />
          </svg>
        </span>
      </button>
      {open && <p className="pb-5 text-gray-600 leading-relaxed text-sm">{a}</p>}
    </div>
  );
}

export default function FaqPage() {
  const navigate = useNavigate();
  const isCounselor = isCounselorSubdomain();
  const [contactForm, setContactForm] = useState({ name: '', email: '', message: '' });
  const [sent, setSent] = useState(false);

  const PLATFORM = isCounselor ? 'Kaunselor' : 'VeriRec';
  const EMAIL = isCounselor ? 'hello@kaunselor.app' : 'hello@verirec.app';
  const faqs = isCounselor ? KAUNSELOR_FAQS : VERIREC_FAQS;
  const accentHover = isCounselor ? 'text-violet-600' : 'text-blue-600';

  const handleContact = (e) => {
    e.preventDefault();
    window.location.href = `mailto:${EMAIL}?subject=Enquiry from ${contactForm.name}&body=${encodeURIComponent(contactForm.message)}%0A%0AFrom: ${contactForm.name} (${contactForm.email})`;
    setSent(true);
  };

  return (
    <>
    <Helmet>
      <title>Frequently Asked Questions — {PLATFORM}</title>
      <meta name="description" content={isCounselor
        ? 'Answers to common questions about Kaunselor — privacy compliance, client bookings, AI session reports, assessments, pricing, and support.'
        : 'Answers to common questions about VeriRec — PDPA compliance, data security, transcription, audio recording, and pricing plans.'
      } />
      <link rel="canonical" href={isCounselor ? 'https://kaunselor.app/faq' : 'https://www.verirec.app/faq'} />
    </Helmet>
    <div className="min-h-screen bg-gray-50">
      {/* Nav */}
      <nav className="bg-white border-b px-6 py-4 flex items-center justify-between">
        <button onClick={() => navigate('/')} className="flex items-center gap-2">
          {isCounselor ? (
            <>
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" className="w-8 h-8">
                <rect width="32" height="32" rx="8" fill="#8b5cf6"/>
                <polyline points="4,16 7,11 10,21 13,9 16,23 19,11 22,18 25,14 28,16"
                  stroke="white" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round" fill="none"/>
              </svg>
              <span className="font-bold text-gray-900">Kaunselor</span>
            </>
          ) : (
            <>
              <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" className="w-8 h-8">
                <rect width="32" height="32" rx="8" fill="#2563eb"/>
                <polyline points="4,16 7,11 10,21 13,9 16,23 19,11 22,18 25,14 28,16"
                  stroke="white" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round" fill="none"/>
              </svg>
              <span className="font-bold text-gray-900">VeriRec</span>
            </>
          )}
        </button>
        <Button size="sm" variant={isCounselor ? 'primary' : 'primary'}
          className={isCounselor ? 'bg-violet-600 hover:bg-violet-700' : ''}
          onClick={() => navigate('/auth')}>
          Sign In
        </Button>
      </nav>

      <div className="max-w-3xl mx-auto px-6 py-16">
        <div className="text-center mb-12">
          <h1 className="text-3xl font-bold text-gray-900">Frequently Asked Questions</h1>
          <p className="text-gray-500 mt-3">Common questions about {PLATFORM}</p>
        </div>

        <div className="bg-white rounded-2xl border p-6 mb-12">
          {faqs.map((faq, i) => <FaqItem key={i} q={faq.q} a={faq.a} accent={accentHover} />)}
        </div>

        {/* Contact */}
        <div className="bg-white rounded-2xl border p-8">
          <h2 className="text-xl font-bold text-gray-900 mb-2">Still have questions?</h2>
          <p className="text-gray-500 text-sm mb-6">Contact us and we'll get back to you within 24 hours.</p>

          {sent ? (
            <div className="text-center py-8">
              <div className="text-4xl mb-3">✓</div>
              <p className="font-medium text-gray-900">Message sent.</p>
              <p className="text-sm text-gray-500 mt-1">We'll reply to your email within 24 hours.</p>
            </div>
          ) : (
            <form onSubmit={handleContact} className="space-y-4">
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Name</label>
                  <input
                    type="text" required
                    value={contactForm.name}
                    onChange={e => setContactForm(p => ({ ...p, name: e.target.value }))}
                    className={`w-full rounded-lg border border-gray-300 px-3 py-2 text-sm focus:outline-none focus:ring-2 ${isCounselor ? 'focus:ring-violet-500' : 'focus:ring-blue-500'}`}
                    placeholder="Your full name"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Email</label>
                  <input
                    type="email" required
                    value={contactForm.email}
                    onChange={e => setContactForm(p => ({ ...p, email: e.target.value }))}
                    className={`w-full rounded-lg border border-gray-300 px-3 py-2 text-sm focus:outline-none focus:ring-2 ${isCounselor ? 'focus:ring-violet-500' : 'focus:ring-blue-500'}`}
                    placeholder="your@email.com"
                  />
                </div>
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Message</label>
                <textarea
                  required rows={4}
                  value={contactForm.message}
                  onChange={e => setContactForm(p => ({ ...p, message: e.target.value }))}
                  className={`w-full rounded-lg border border-gray-300 px-3 py-2 text-sm focus:outline-none focus:ring-2 ${isCounselor ? 'focus:ring-violet-500' : 'focus:ring-blue-500'}`}
                  placeholder="Write your question or enquiry here..."
                />
              </div>
              <Button type="submit"
                className={isCounselor ? 'bg-violet-600 hover:bg-violet-700 w-full sm:w-auto' : 'w-full sm:w-auto'}>
                Send Message
              </Button>
            </form>
          )}
        </div>
      </div>
    </div>
    </>
  );
}
